import type { Metadata } from "next";
import Link from "next/link";
import { Card, SectionHeading, Notice } from "@/components/ui";
import { LangText } from "@/components/lang-text";

export const metadata: Metadata = { title: "Privacy", description: "How your data stays private in your browser.", alternates: { canonical: "/privacy" } };

export default function Privacy() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <SectionHeading kicker={<LangText en="Privacy" ta="தனியுரிமை" />} title={<LangText en="Private by default" ta="இயல்பாகவே தனிப்பட்டது" />} desc={<LangText en="No account. No tracking pixels. No sale of data." ta="கணக்கு இல்லை. கண்காணிப்பு இல்லை. தரவு விற்பனை இல்லை." />} />
      <div className="grid gap-4">
        <Card className="min-w-0"><h2 className="font-bold"><LangText en="Where your data lives" ta="உங்கள் தரவு எங்கு உள்ளது" /></h2><p className="mt-2 text-sm"><LangText en="Your data is stored locally in this browser. It is not uploaded by this application. Export your data before clearing browser storage or changing devices." ta="உங்கள் தரவு இந்த உலாவியில் உள்ளூரில் சேமிக்கப்படுகிறது. இந்தச் செயலி அதைப் பதிவேற்றாது. உலாவித் தரவை அழிக்கும் முன் அல்லது சாதனம் மாறும் முன் ஏற்றுமதி செய்யுங்கள்." /></p><p className="mt-2 text-sm"><LangText en="Assessment answers, results, flow entries, journal, plan, and circle are stored in your browser’s localStorage under versioned keys starting with ikigai.v1. Nothing is sent to any server by this application. Local storage is convenient, not encrypted — anyone with access to this browser profile could read it." ta="மதிப்பீடு, முடிவுகள், ஒன்றிப்பு, நாட்குறிப்பு, திட்டம், வட்டம் ஆகியவை ikigai.v1 என்ற பதிப்பு விசைகளில் உலாவி சேமிப்பில் உள்ளன. எதுவும் சேவையகத்திற்கு அனுப்பப்படாது. உள்ளூர் சேமிப்பு வசதியானது, மறையாக்கம் செய்யப்பட்டதல்ல." /></p></Card>
        <Card className="min-w-0"><h2 className="font-bold"><LangText en="Export" ta="ஏற்றுமதி" /></h2><p className="mt-2 text-sm"><LangText en="Download one versioned JSON file (format: ikigai-export, version: 1) containing your answers, results, flow, plan, journal, circle, and preferences — nothing else. Use Dashboard → Export all data. Store the file somewhere safe; it contains your private reflections." ta="உங்கள் பதில்கள், முடிவுகள், ஒன்றிப்பு, திட்டம், நாட்குறிப்பு, வட்டம், விருப்பங்கள் அடங்கிய ஒரு பதிப்பு JSON கோப்பைப் (ikigai-export, பதிப்பு 1) பதிவிறக்குங்கள் — வேறு எதுவும் இல்லை. பலகை → ஏற்றுமதி. கோப்பைப் பாதுகாப்பாக வையுங்கள்; அதில் தனிப்பட்ட சிந்தனைகள் உள்ளன." /></p></Card>
        <Card className="min-w-0"><h2 className="font-bold"><LangText en="Import" ta="இறக்குமதி" /></h2><p className="mt-2 text-sm"><LangText en="On a new device or browser, use Dashboard → Import from file. Only files you exported from this app are accepted (JSON, 5 MB limit, validated before anything changes). You will see a preview of what the file contains, and replacing happens only after you confirm. Your current data stays untouched if the file is invalid." ta="புது சாதனம்/உலாவியில் பலகை → கோப்பிலிருந்து இறக்குமதி. இந்தச் செயலியின் ஏற்றுமதிக் கோப்புகள் மட்டும் (JSON, 5 MB வரம்பு, மாற்றத்திற்கு முன் சரிபார்ப்பு). முன்னோட்டம் காட்டப்படும்; உறுதி செய்த பின்னரே மாற்றம். கோப்பு தவறானால் தற்போதைய தரவு மாறாது." /></p></Card>
        <Card className="min-w-0"><h2 className="font-bold"><LangText en="Delete" ta="நீக்கு" /></h2><p className="mt-2 text-sm"><LangText en="Delete single entries where they live, or everything at once (Dashboard → Delete all data, with confirmation). Clearing browser site data or uninstalling the browser profile also removes local data — export first." ta="தனிப் பதிவுகளை அந்தந்த இடத்தில் நீக்குங்கள், அல்லது அனைத்தையும் ஒரேயடியாக (பலகை → அனைத்தும் நீக்கு, உறுதியுடன்). உலாவித் தரவை அழித்தாலும் உள்ளூர் தரவு நீங்கும் — முதலில் ஏற்றுமதி செய்க." /></p></Card>
        <Card className="min-w-0"><h2 className="font-bold"><LangText en="Limits of browser storage" ta="உலாவிச் சேமிப்பின் வரம்புகள்" /></h2><p className="mt-2 text-sm"><LangText en="Clearing browser data, using private mode, changing devices or browsers may remove your data. Private browsing may block storage entirely — the app then keeps data only in memory until you close the tab. Export JSON/Markdown regularly from Dashboard, Journal, Flow, and Results." ta="உலாவித் தரவை அழித்தால், தனிப்பட்ட உலாவல், சாதனம்/உலாவி மாற்றம் தரவை நீக்கலாம். தனிப்பட்ட உலாவல் சேமிப்பைத் தடுக்கலாம் — தாவலை மூடும் வரை நினைவகத்தில் மட்டும் இருக்கும். பலகை, நாட்குறிப்பு, ஒன்றிப்பு, முடிவுகளிலிருந்து தவறாமல் ஏற்றுமதி செய்க." /></p></Card>
        <Card className="min-w-0"><h2 className="font-bold"><LangText en="Your controls" ta="உங்கள் கட்டுப்பாடுகள்" /></h2><ul className="mt-2 list-disc pl-5 text-sm"><LangText en={<><li>Export all data (Dashboard → Export all data).</li><li>Import a previous export (Dashboard → Import from file).</li><li>Delete per-item or per-section with confirmation.</li><li>Delete everything (Dashboard → Delete all data).</li></>} ta={<><li>அனைத்துத் தரவையும் ஏற்றுமதி (பலகை → ஏற்றுமதி).</li><li>முந்தைய ஏற்றுமதியை இறக்குமதி (பலகை → கோப்பிலிருந்து).</li><li>தனிப்பதிவு/பகுதி நீக்கம் உறுதியுடன்.</li><li>அனைத்தும் நீக்கு (பலகை → அனைத்தும் நீக்கு).</li></>} /></ul>
        <p className="mt-3"><Link href="/dashboard" className="inline-block rounded-full bg-midnight px-5 py-2.5 text-sm font-semibold text-champagne dark:bg-imperial dark:text-obsidian"><LangText en="Open Dashboard data controls" ta="பலகை தரவுக் கட்டுப்பாடுகள்" /></Link></p></Card>
        <Card className="min-w-0"><h2 className="font-bold"><LangText en="What we do not collect" ta="நாங்கள் சேகரிக்காதவை" /></h2><p className="mt-2 text-sm"><LangText en="No analytics unless you self-host and configure it. No advertising identifiers. No personal data beyond what you type — and that stays with you." ta="நீங்களே நிறுவித் தகவமைத்தாலன்றி பகுப்பாய்வு இல்லை. விளம்பர அடையாளங்கள் இல்லை. நீங்கள் தட்டச்சு செய்வதைத் தாண்டி எதுவும் இல்லை — அதுவும் உங்களிடமே." /></p></Card>
        <Notice><LangText en="No API keys are required. No backend is used in version one." ta="API விசைகள் தேவையில்லை. முதல் பதிப்பில் பின்தளம் இல்லை." /></Notice>
      </div>
    </div>
  );
}
